# Generated by Django 2.2.3 on 2019-12-12 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhUsers',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='登录密码')),
                ('paypwd', models.CharField(blank=True, max_length=50, null=True, verbose_name='支付密码')),
                ('reg_time', models.DateTimeField(blank=True, null=True, verbose_name='注册时间')),
                ('last_ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='登录ip')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True, verbose_name='昵称')),
                ('head_pic', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='手机号')),
                ('is_lock', models.SmallIntegerField(blank=True, null=True, verbose_name='是否锁定')),
                ('tjr_id', models.IntegerField(blank=True, null=True, verbose_name='推荐人id')),
                ('totalnum', models.IntegerField(blank=True, null=True, verbose_name='团队人数')),
                ('ztnum', models.IntegerField(blank=True, null=True, verbose_name='直推人数')),
                ('idcard', models.CharField(blank=True, max_length=50, null=True, verbose_name='身份证号')),
                ('is_shiming', models.SmallIntegerField(blank=True, null=True, verbose_name='是否实名')),
                ('realname', models.CharField(blank=True, max_length=50, null=True, verbose_name='实名姓名')),
                ('self_htlv', models.FloatField(blank=True, null=True, verbose_name='个人回头率')),
                ('total_htlv', models.FloatField(blank=True, null=True, verbose_name='团队回头率')),
                ('big_htlv', models.FloatField(blank=True, null=True, verbose_name='大区回头率')),
                ('small_htlv', models.FloatField(blank=True, null=True, verbose_name='小区回头率')),
                ('is_shiming_zs', models.SmallIntegerField(blank=True, null=True, verbose_name='是否实名赠送')),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='推广二维码')),
                ('first_read', models.DateTimeField(blank=True, null=True, verbose_name='今日首次阅读时间')),
                ('tmp_read', models.DateTimeField(blank=True, null=True, verbose_name='今日完成阅读时间')),
                ('appid', models.CharField(blank=True, max_length=100, null=True, verbose_name='设备号（不可修改）')),
                ('user_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='连接密匙')),
            ],
            options={
                'db_table': 'wh_users',
            },
        ),
        migrations.CreateModel(
            name='WhWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(blank=True, null=True, verbose_name='余额（￥）')),
                ('wechat', models.CharField(blank=True, max_length=255, null=True, verbose_name='微信')),
                ('alipay', models.CharField(blank=True, max_length=255, null=True, verbose_name='支付宝')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.WhUsers', verbose_name='关联用户')),
            ],
            options={
                'db_table': 'wh_wallet',
            },
        ),
        migrations.CreateModel(
            name='WhPayOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(blank=True, null=True, verbose_name='支付金额')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='支付类型')),
                ('order_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='订单号')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('status', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='支付状态')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.WhUsers', verbose_name='关联用户')),
            ],
            options={
                'db_table': 'wh_pay_order',
            },
        ),
        migrations.CreateModel(
            name='WhMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='发送状态')),
                ('send_time', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('msg', models.CharField(blank=True, max_length=255, null=True, verbose_name='内容')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.WhUsers', verbose_name='关联用户')),
            ],
            options={
                'db_table': 'wh_message',
            },
        ),
        migrations.CreateModel(
            name='WhDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(blank=True, null=True, verbose_name='交易金额')),
                ('status', models.SmallIntegerField(blank=True, null=True, verbose_name='状态')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='交易时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.WhUsers', verbose_name='关联用户')),
            ],
            options={
                'db_table': 'wh_detail',
            },
        ),
        migrations.CreateModel(
            name='WhCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_money', models.FloatField(blank=True, null=True, verbose_name='支付金额')),
                ('order_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='订单号')),
                ('set_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('status', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='支付状态')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.WhUsers', verbose_name='关联用户')),
            ],
            options={
                'db_table': 'wh_certification',
            },
        ),
    ]
