# Generated by Django 2.2.7 on 2019-12-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhCertification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_money', models.FloatField(blank=True, null=True)),
                ('order_num', models.CharField(blank=True, max_length=50, null=True)),
                ('set_time', models.DateTimeField(blank=True, null=True)),
                ('pay_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wh_certification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WhDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('money', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wh_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WhMessage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('send_time', models.DateTimeField(blank=True, null=True)),
                ('msg', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'wh_message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WhPayOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('money', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('order_num', models.CharField(blank=True, max_length=100, null=True)),
                ('pay_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wh_pay_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WhUsers',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('paypwd', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_time', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('head_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('is_lock', models.SmallIntegerField(blank=True, null=True)),
                ('tjr_id', models.IntegerField(blank=True, null=True)),
                ('totalnum', models.IntegerField(blank=True, null=True)),
                ('ztnum', models.IntegerField(blank=True, null=True)),
                ('idcard', models.CharField(blank=True, max_length=50, null=True)),
                ('is_shiming', models.SmallIntegerField(blank=True, null=True)),
                ('realname', models.CharField(blank=True, max_length=50, null=True)),
                ('self_htlv', models.FloatField(blank=True, null=True)),
                ('total_htlv', models.FloatField(blank=True, null=True)),
                ('big_htlv', models.FloatField(blank=True, null=True)),
                ('small_htlv', models.FloatField(blank=True, null=True)),
                ('is_shiming_zs', models.SmallIntegerField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('first_read', models.DateTimeField(blank=True, null=True)),
                ('tmp_read', models.DateTimeField(blank=True, null=True)),
                ('appid', models.CharField(blank=True, max_length=100, null=True)),
                ('user_key', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'wh_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WhWallet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('money', models.FloatField(blank=True, null=True)),
                ('wechat', models.CharField(blank=True, max_length=255, null=True)),
                ('alipay', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'wh_wallet',
                'managed': False,
            },
        ),
    ]
