# Generated by Django 2.2.3 on 2019-12-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20191210_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='whbanner',
            name='is_show',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='是否显示'),
        ),
        migrations.AddField(
            model_name='whbanner',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='广告名字'),
        ),
        migrations.AddField(
            model_name='whbanner',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='广告位置'),
        ),
    ]
