# Generated by Django 2.2.3 on 2019-12-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20191213_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhBanPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='广告名称')),
                ('wight', models.IntegerField(blank=True, max_length=11, null=True, verbose_name='广告宽度')),
                ('height', models.IntegerField(blank=True, max_length=11, null=True, verbose_name='广告高度')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='广告描述')),
                ('status', models.SmallIntegerField(blank=True, null=True, verbose_name='广告状态')),
            ],
            options={
                'db_table': 'wh_ban_place',
            },
        ),
    ]
