# Generated by Django 2.2.3 on 2019-12-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_whbanplace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whbanplace',
            old_name='desc',
            new_name='adv_desc',
        ),
        migrations.RemoveField(
            model_name='whbanner',
            name='place',
        ),
        migrations.AddField(
            model_name='whbanner',
            name='place_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='广告位置'),
        ),
        migrations.AlterField(
            model_name='whbanplace',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='广告高度'),
        ),
        migrations.AlterField(
            model_name='whbanplace',
            name='wight',
            field=models.IntegerField(blank=True, null=True, verbose_name='广告宽度'),
        ),
    ]
