# Generated by Django 2.2.7 on 2019-11-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('img', models.CharField(blank=True, db_column='Img', max_length=255, null=True)),
                ('author', models.CharField(blank=True, db_column='Author', max_length=100, null=True)),
                ('desc', models.TextField(blank=True, db_column='Desc', null=True)),
                ('cid', models.IntegerField(blank=True, db_column='CId', null=True)),
                ('cname', models.CharField(blank=True, db_column='CName', max_length=100, null=True)),
                ('bookstatus', models.CharField(blank=True, db_column='BookStatus', max_length=20, null=True)),
                ('add_time', models.IntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, db_column='Score', decimal_places=2, max_digits=12, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('renqi', models.IntegerField(blank=True, db_column='Renqi', null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('lasttime', models.IntegerField(blank=True, db_column='LastTime', null=True)),
                ('is_show', models.PositiveIntegerField()),
                ('lastchapterid', models.IntegerField(blank=True, db_column='LastChapterId', null=True)),
                ('lastchapter', models.CharField(blank=True, db_column='LastChapter', max_length=255, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('sytype', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sy_book',
                'managed': False,
            },
        ),
    ]
