# Generated by Django 2.2.7 on 2019-12-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('img', models.CharField(blank=True, max_length=255, null=True, verbose_name='Img')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Author')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Desc')),
                ('cid', models.IntegerField(blank=True, null=True, verbose_name='CId')),
                ('cname', models.CharField(blank=True, max_length=100, null=True, verbose_name='CName')),
                ('bookstatus', models.CharField(blank=True, max_length=20, null=True, verbose_name='BookStatus')),
                ('add_time', models.IntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Score')),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('renqi', models.IntegerField(blank=True, null=True, verbose_name='Renqi')),
                ('week', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('lasttime', models.IntegerField(blank=True, null=True, verbose_name='LastTime')),
                ('is_show', models.PositiveIntegerField()),
                ('lastchapterid', models.IntegerField(blank=True, null=True, verbose_name='LastChapterId')),
                ('lastchapter', models.CharField(blank=True, max_length=255, null=True, verbose_name='LastChapter')),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('sytype', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sy_book',
                'managed': False,
            },
        ),
    ]
