# Generated by Django 2.2.7 on 2019-12-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='书名')),
                ('b_img', models.CharField(blank=True, max_length=255, null=True, verbose_name='封面图片')),
                ('b_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('b_auhtor', models.CharField(blank=True, max_length=100, null=True, verbose_name='作者')),
                ('b_content_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='内容地址')),
                ('add_time', models.DateTimeField(blank=True, null=True, verbose_name='上传时间')),
                ('read_num', models.IntegerField(blank=True, null=True, verbose_name='阅读量')),
                ('new_chapter', models.CharField(blank=True, max_length=50, null=True, verbose_name='最新章节')),
            ],
            options={
                'db_table': 'wh_book',
            },
        ),
        migrations.CreateModel(
            name='WhNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'wh_notice',
            },
        ),
        migrations.CreateModel(
            name='WhReadlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('book_id', models.IntegerField(verbose_name='小说ID')),
            ],
            options={
                'db_table': 'wh_readlog',
            },
        ),
        migrations.CreateModel(
            name='WhTypeOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tap_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='一级分类名称')),
            ],
            options={
                'db_table': 'wh_type_one',
            },
        ),
        migrations.CreateModel(
            name='WhTypeChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='二级分类名称')),
                ('t', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.WhTypeOne', verbose_name='一级分类id')),
            ],
            options={
                'db_table': 'wh_type_child',
            },
        ),
        migrations.CreateModel(
            name='WhCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='章节名称')),
                ('add_time', models.DateTimeField(blank=True, null=True, verbose_name='添加时间')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.WhBook', verbose_name='关联小说')),
            ],
            options={
                'db_table': 'wh_catalog',
            },
        ),
        migrations.AddField(
            model_name='whbook',
            name='c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.WhTypeChild', verbose_name='关联二级分类'),
        ),
    ]
