# Generated by Django 2.2.3 on 2019-12-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whbook',
            name='add_time',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='whcatalog',
            name='add_time',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='添加时间'),
        ),
    ]
