# Generated by Django 2.2.3 on 2019-12-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whadmin',
            name='last_login_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='上次登录时间'),
        ),
        migrations.AlterField(
            model_name='whadmin',
            name='login_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='登录时间'),
        ),
    ]
