# Generated by Django 2.2.3 on 2019-12-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20191210_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whadmin',
            name='add_time',
            field=models.DateField(auto_now_add=True, verbose_name='添加时间'),
        ),
    ]
