# Generated by Django 2.2.3 on 2019-12-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20191210_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whadmin',
            name='add_time',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='whadmin',
            name='last_login_time',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='上次登录时间'),
        ),
        migrations.AlterField(
            model_name='whadmin',
            name='login_time',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='登录时间'),
        ),
        migrations.AlterField(
            model_name='whadminlog',
            name='add_time',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='whadminrole',
            name='add_time',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='whorganization',
            name='add_time',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='创建时间'),
        ),
    ]
